name: CI and Publish

on:
  push:
    branches: [development, master]
  pull_request:
    branches: [development, master]

permissions:
  contents: write
  id-token: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm install
      - run: npm test
      - name: Save test result
        uses: actions/upload-artifact@v3
        with:
          name: test-result
          path: ./test-results

  publish:
    runs-on: ubuntu-latest
    needs: build
    if: needs.build.result == 'success' && github.ref == 'refs/heads/master'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'
          registry-url: 'https://registry.npmjs.org/'

      - name: Set up Git
        run: |
          git config --global user.email "miladezzat.f@gmail.com"
          git config --global user.name "Milad E. Fahmy"

      - run: npm install
      - run: npm run build
      - run: npm run release -- --release-as ${{ env.RELEASE_TYPE }}
        env:
          RELEASE_TYPE: ${{ secrets.RELEASE_TYPE }}
      
      - name: Push changes to master branch
        run: |
          git push --follow-tags
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to npm
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}

      - name: Handle development branch
        run: |
          git fetch origin
          git checkout development
          git pull origin development
          git reset --hard origin/master
          git push origin development
          
